import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#faf9f6",
        "surface-dim": "#dbdad7",
        "surface-bright": "#faf9f6",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f3f1",
        "surface-container": "#efeeeb",
        "surface-container-high": "#e9e8e5",
        "surface-container-highest": "#e3e2e0",
        "on-surface": "#1a1c1a",
        "on-surface-variant": "#444748",
        "inverse-surface": "#2f312f",
        "inverse-on-surface": "#f2f1ee",
        "outline": "#747878",
        "outline-variant": "#c4c7c7",
        "primary": "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#1c1b1b",
        "on-primary-container": "#858383",
        "secondary": "#605e5c",
        "on-secondary": "#ffffff",
        "secondary-container": "#e6e2de",
        "on-secondary-container": "#666461",
        "tertiary": "#000000",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        background: "#faf9f6",
        foreground: "#1a1c1a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.25rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1440px",
        "gutter": "24px",
        "stack-md": "16px",
        "stack-sm": "8px",
        "section-gap": "120px",
        "margin-mobile": "20px",
        "stack-lg": "32px",
        "margin-desktop": "64px",
      },
      fontFamily: {
        serif: ["var(--font-bodoni)", "Bodoni Moda", "serif"],
        sans: ["var(--font-inter)", "Inter", "sans-serif"],
        "display-hero": ["var(--font-bodoni)", "Bodoni Moda", "serif"],
        "headline-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-caps": ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "caption": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0.01em", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "display-hero": ["80px", { lineHeight: "96px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "0em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
