import { Category } from "@/types/category";

export interface CategoryWithSubcategories extends Category {
  subcategories: string[];
}

export const INITIAL_CATEGORIES: CategoryWithSubcategories[] = [
  {
    id: "cat_fragrance",
    name: "Fragrance",
    slug: "fragrance",
    description: "Compounding oils, artisan perfume bases, essential oils, and concentrated aromatic raw materials.",
    sortOrder: 1,
    active: true,
    subcategories: [
      "Fragrance Oils",
      "Perfume Bases",
      "Essential Oils",
      "Fragrance Concentrates",
    ],
    createdAt: "2026-08-23T00:00:00Z",
    updatedAt: "2026-08-23T00:00:00Z",
  },
  {
    id: "cat_bottles",
    name: "Bottles",
    slug: "bottles",
    description: "Flint glass roll-ons, travel fine mist atomizers, and lab storage containers across all standard volumetric capacities.",
    sortOrder: 2,
    active: true,
    subcategories: [
      "Vidrio",
      "Plástico HDPE",
    ],
    createdAt: "2026-08-23T00:00:00Z",
    updatedAt: "2026-08-23T00:00:00Z",
  },
  {
    id: "cat_packaging",
    name: "Packaging",
    slug: "packaging",
    description: "110 lb die-cut perfume boxes, kraft hang tags, holographic security seals, and POF heat shrink wrap bags.",
    sortOrder: 3,
    active: true,
    subcategories: [
      "Boxes",
      "Tags",
      "Security Stickers",
      "Labels",
      "Heat Shrink Wrap Bags",
    ],
    createdAt: "2026-08-23T00:00:00Z",
    updatedAt: "2026-08-23T00:00:00Z",
  },
  {
    id: "cat_tools",
    name: "Tools",
    slug: "tools",
    description: "Graduated transfer pipettes, precision dosing droppers, funnels, and volumetric measuring equipment.",
    sortOrder: 4,
    active: true,
    subcategories: [
      "Pipettes",
      "Droppers",
      "Funnels",
      "Measuring Tools",
    ],
    createdAt: "2026-08-23T00:00:00Z",
    updatedAt: "2026-08-23T00:00:00Z",
  },
  {
    id: "cat_testing",
    name: "Testing",
    slug: "testing",
    description: "Absorbent cotton blotter test strips, sample vials, and olfactory testing accessories.",
    sortOrder: 5,
    active: true,
    subcategories: [
      "Blotter Strips",
      "Sample Bottles",
      "Testers",
    ],
    createdAt: "2026-08-23T00:00:00Z",
    updatedAt: "2026-08-23T00:00:00Z",
  },
  {
    id: "cat_custom",
    name: "Custom",
    slug: "custom",
    description: "Precision-cut waterproof vinyl and hot metallic foil labels engineered directly to bottle diameters, plus custom tags and boxes.",
    sortOrder: 6,
    active: true,
    subcategories: [
      "Custom Perfume Labels",
      "Custom Tags",
      "Custom Boxes",
    ],
    createdAt: "2026-08-23T00:00:00Z",
    updatedAt: "2026-08-23T00:00:00Z",
  },
  {
    id: "cat_kits",
    name: "Kits",
    slug: "kits",
    description: "Turnkey starter sets for roll-on creation, discovery sampling, and perfumery business launching.",
    sortOrder: 7,
    active: true,
    subcategories: [
      "Beginner Perfume Kit",
      "Roll-On Kit",
      "Sample Kit",
      "Perfume Business Kit",
      "Packaging Kit",
    ],
    createdAt: "2026-08-23T00:00:00Z",
    updatedAt: "2026-08-23T00:00:00Z",
  },
  {
    id: "cat_wholesale",
    name: "Wholesale",
    slug: "wholesale",
    description: "High-volume master case quantities (500 to 10,000+ units) with dedicated freight schedules.",
    sortOrder: 8,
    active: true,
    subcategories: [
      "500+ Units",
      "1,000+ Units",
      "2,500+ Units",
      "5,000+ Units",
      "10,000+ Units",
    ],
    createdAt: "2026-08-23T00:00:00Z",
    updatedAt: "2026-08-23T00:00:00Z",
  },
];
